ALTER TABLE financeiro.clientes
  ADD COLUMN IF NOT EXISTS cep         VARCHAR(10),
  ADD COLUMN IF NOT EXISTS logradouro  VARCHAR(255),
  ADD COLUMN IF NOT EXISTS numero      VARCHAR(20),
  ADD COLUMN IF NOT EXISTS complemento VARCHAR(100),
  ADD COLUMN IF NOT EXISTS bairro      VARCHAR(100),
  ADD COLUMN IF NOT EXISTS municipio   VARCHAR(100),
  ADD COLUMN IF NOT EXISTS uf          CHAR(2);
